# .github/snk-config.yaml

github_user_name: Rakshithg6

theme:
  # Make sure we set a dark background to avoid white issues
  background: "#0d1117"

  # Snake color (e.g., purple)
  color_snake: "#8a2be2"

  # Dot contribution colors (fitting for dark mode)
  color_dots: ["#161b22", "#30363d", "#484f58", "#6e7681", "#8b949e"]
