palette:
  background: "#1A1A2E"  # Dark background similar to the image
  snake: "#00FF00"       # Green snake
  tail: "#FF00FF"        # Purple tail/food
  grid: "#2E2E48"        # Subtle gray grid
