# .github/snk-config.yaml

github_user_name: Rakshithg6

theme:
  background: "#000000"  # Full black color for better visibility
  color_snake: "#8a2be2"  # Keep your snake color or update for contrast
  color_dots: ["#111111", "#222222", "#333333", "#444444", "#555555"]  # Gradient shades for better visibility
