name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight
  workflow_dispatch:      # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTION_TOKEN }}

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: update GitHub contribution snake"
          file_pattern: "output/*.svg"
