name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: jamesgeorge007/github-readme-stats@v4  # Corrected action name
        with:
          token: ${{ secrets.CONTRIBUTION_TOKEN }}
          user: ${{ github.repository_owner }}
          count_private: "true"
          include_all_commits: "true"
          output: output/github-contribution-grid-snake.svg
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: update github contribution snake"
          push_options: "--force"
