name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets..CONTRIBUTION_TOKEN }}
          OUTPUT_PATH: ./output/github-contribution-grid-snake-dark.svg
          COLOR_THEME: dark
          # Add any other customization options here (see documentation)
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: update github contribution snake"
          push_options: "--force"
