name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.CONTRIBUTION_TOKEN }}
          user_name: ${{ github.repository_owner }}
          output_path: ./output/github-contribution-grid-snake-dark.svg
          color_theme: dark
          show_activity: true
          show_activity_streak: true
          show_total_contributions: true
          target_branch: main
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: update github contribution snake"
          push_options: "--force"
